"""empty message

Revision ID: 505bc8c73a8c
Revises: 5f03543f6518
Create Date: 2022-08-02 16:52:29.468576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505bc8c73a8c'
down_revision = '5f03543f6518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('availability', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'availability')
    # ### end Alembic commands ###
